name: CI/CD Pipeline

on:
  push:
    branches:
      - main     # production
      - develop  # staging
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          cd backend
          npm install
          npm test
      - run: |
          cd backend
          npx prisma migrate deploy
      - run: echo "Deploy backend here"

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: |
          cd frontend
          npm install
          npm test
          npm run build
      - run: echo "Deploy frontend here"